"""New revision1

Revision ID: 6c57db4177b5
Revises: 9c9c3f70b407
Create Date: 2021-02-20 01:12:55.780865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c57db4177b5'
down_revision = '9c9c3f70b407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
