"""New revision4

Revision ID: 6d6241a56552
Revises: b7f6863ab381
Create Date: 2021-02-20 12:28:49.923959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6241a56552'
down_revision = 'b7f6863ab381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('user_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bank_account', 'user', ['user_pk'], ['pk'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_account', type_='foreignkey')
    op.drop_column('bank_account', 'user_pk')
    # ### end Alembic commands ###
