"""New revision3

Revision ID: b7f6863ab381
Revises: 078e40a2b7b6
Create Date: 2021-02-20 12:19:08.495332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f6863ab381'
down_revision = '078e40a2b7b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
